# This file pushes the choco package for Corretto-11

name: Corretto-11 choco push workflow

on:
  workflow_dispatch:
  push:
    paths:
    - 'corretto-jdk-11/corretto11jdk.nuspec'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: corretto-jdk-11 
        shell: powershell
        run: |
          cd corretto-jdk-11
          choco pack
          choco upgrade corretto11jdk --source .
          choco push --source https://push.chocolatey.org/ -k $env:CHOCO_KEY
        env:
          CHOCO_KEY: ${{ secrets.CHOCO_KEY }}
