# This file pushes the choco package for Corretto-8

name: Corretto-8 choco push workflow

on:
  workflow_dispatch:
  push:
    paths:
    - 'corretto-jdk-8/corretto8jdk.nuspec'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: corretto-jdk-8 
        shell: powershell
        run: |
          cd corretto-jdk-8
          choco pack
          choco upgrade corretto8jdk --source .
          choco push --source https://push.chocolatey.org/ -k $env:CHOCO_KEY
        env:
          CHOCO_KEY: ${{ secrets.CHOCO_KEY }}
