# This file pushes the choco package for Corretto Base version

name: Corretto Base version choco push workflow

on:
  workflow_dispatch:
  push:
    paths:
    - 'corretto-jdk/correttojdk.nuspec'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: corretto-jdk
        shell: powershell
        run: |
          cd corretto-jdk
          choco pack
          choco upgrade correttojdk --source .
          choco push --source https://push.chocolatey.org/ -k $env:CHOCO_KEY
        env:
          CHOCO_KEY: ${{ secrets.CHOCO_KEY }}
