# This file updates the NUSPEC(s) in the repo checking the API

name: Zulu nuspec updater

on:
  schedule:
    - cron: "41 23 * * *"
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || github.token }}
      - name:
        shell: bash
        run: |
          ./scripts/zulu-sync.sh >> $GITHUB_OUTPUT
        id: zulu_sync
      - name:
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || github.token }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "${{join(steps.zulu_sync.outputs.*, '\n')}}"
          git push



