# This file pushes the choco package for zulu

name: Zulu choco push workflow

on:
  push:
    paths:
    - 'zulu/zulu.nuspec'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: ultimate
        shell: powershell
        run: |
          cd zulu
          choco pack
          choco upgrade zulu --source .
          choco push --source https://push.chocolatey.org/ -k $env:CHOCO_KEY
        env:
          CHOCO_KEY: ${{ secrets.CHOCO_KEY }}
